config:
  colors:
    white_up: [.8,.8,.8]
    white_down: [1,1,1]
    black_up: [.2,.2,.2]
    black_down: [.4,.4,.4]
  video:
    frameRate: 25
    numFrames: 174
    size: [1280,720]
    seed: "default"
  info:
    title: "Title"
    author: "Author"
    debug: true
  files:
    mp4Filename: "../files/out.mp4"
    imagesPath: "../files/out-{}.png"
